function indent(code) {
  return code.split("\n").map(line => "  " + line).join("\n")
}

function generateBlock(statements) {
  if (statements.length === 0) return "{}"
  return "{\n" + indent(statements.map(generate).join("\n")) + "\n}"
}

const generators = {
  Program(node) {
    return [
      "// Generated by the Rex Script Compiler",
      ...node.statements.map(generate),
    ].join("\n")
  },

  FunctionDeclaration(node) {
    const { func, body } = node
    const asyncPrefix = func.isAsync ? "async " : ""
    const params = func.params.map(generate).join(", ")
    return `${asyncPrefix}function ${func.name}(${params}) ${generateBlock(body)}`
  },

  VariableDeclaration(node) {
    return `const ${node.variable.name} = ${generate(node.initializer)}`
  },

  TypeAlias() {
    return ""
  },

  ReturnStatement(node) {
    return `return ${generate(node.expression)}`
  },

  LoopStatement(node) {
    const i = node.variable.name
    const start = generate(node.range.start)
    const end = generate(node.range.end)
    return `for (let ${i} = ${start}; ${i} <= ${end}; ${i}++) ${generateBlock(node.body)}`
  },

  MatchStatement(node) {
    const subject = generate(node.subject)
    const cases = node.arms.map(arm => {
      let body
      if (Array.isArray(arm.body)) {
        const stmts = arm.body.map(generate)
        const last = arm.body[arm.body.length - 1]
        if (!last || last.kind !== "ReturnStatement") stmts.push("break")
        body = stmts.join("\n")
      } else {
        body = generate(arm.body) + "\nbreak"
      }
      if (arm.pattern === "_") {
        return `default:\n${indent(body)}`
      }
      return `case ${generate(arm.pattern)}:\n${indent(body)}`
    })
    return `switch (${subject}) {\n${indent(cases.join("\n"))}\n}`
  },

  GuardStatement(node) {
    return `if (!(${generate(node.condition)})) ${generateBlock(node.elseBlock)}`
  },

  IfStatement(node) {
    const head = `if (${generate(node.test)}) ${generateBlock(node.consequent)}`
    const elseIfs = node.alternates.map(
      a => ` else if (${generate(a.test)}) ${generateBlock(a.consequent)}`
    )
    const tail = node.otherwise ? ` else ${generateBlock(node.otherwise)}` : ""
    return head + elseIfs.join("") + tail
  },

  ThrowStatement(node) {
    return `throw new Error(${generate(node.message)})`
  },

  TryStatement(node) {
    return `try ${generateBlock(node.block)} catch (${node.errorName}) ${generateBlock(node.catchBlock)}`
  },

  ExpressionStatement(node) {
    return `${generate(node.expression)};`
  },

  PipelineExpression(node) {
    const left = generate(node.left)
    const right = node.right
    if (right.kind === "CallExpression") {
      const callee = generate(right.callee)
      const args = [left, ...right.args.map(generate)].join(", ")
      return `${callee}(${args})`
    }
    return `${generate(right)}(${left})`
  },

  BinaryExpression(node) {
    return `${generate(node.left)} ${node.operator} ${generate(node.right)}`
  },

  UnaryExpression(node) {
    return `${node.operator}${generate(node.operand)}`
  },

  TernaryExpression(node) {
    return `${generate(node.condition)} ? ${generate(node.consequent)} : ${generate(node.alternate)}`
  },

  NullCoalesce(node) {
    return `${generate(node.left)} ?? ${generate(node.right)}`
  },

  ExistsExpression(node) {
    const operand = generate(node.operand)
    return `(${operand} !== null && ${operand} !== undefined)`
  },

  AwaitExpression(node) {
    return `await ${generate(node.expression)}`
  },

  CallExpression(node) {
    const callee = generate(node.callee)
    const args = node.args.map(generate).join(", ")
    return `${callee}(${args})`
  },

  MemberExpression(node) {
    const object = generate(node.object)
    if (node.computed) {
      return `${object}[${generate(node.property)}]`
    }
    return `${object}.${node.property}`
  },

  OptionalChain(node) {
    return `${generate(node.object)}?.${node.property}`
  },

  ArrowFunction(node) {
    const params =
      node.params.length === 1
        ? node.params[0].name
        : `(${node.params.map(p => p.name).join(", ")})`
    const body = Array.isArray(node.body)
      ? generateBlock(node.body)
      : generate(node.body)
    return `${params} => ${body}`
  },

  NumericLiteral(node) {
    return String(node.value)
  },

  StringLiteral(node) {
    return JSON.stringify(node.value)
  },

  BooleanLiteral(node) {
    return String(node.value)
  },

  ArrayLiteral(node) {
    return `[${node.elements.map(generate).join(", ")}]`
  },

  ObjectLiteral(node) {
    return `{ ${node.properties.map(generate).join(", ")} }`
  },

  Property(node) {
    return `${node.key}: ${generate(node.value)}`
  },

  TemplateLiteral(node) {
    const body = node.parts
      .map(part => {
        if (part.kind === "TemplateChar") return part.value
        if (part.kind === "Interpolation") return `\${${generate(part.expression)}}`
        return `\${${generate(part)}}`
      })
      .join("")
    return "`" + body + "`"
  },

  FunctionObject(node) {
    return node.name
  },

  Variable(node) {
    return node.name
  },

  Parameter(node) {
    return node.name
  },
}

function generate(node) {
  const gen = generators[node.kind]
  if (!gen) throw new Error(`No generator for node kind: ${node.kind}`)
  return gen(node)
}

export default generate
